### ISSUE TITLE
Build Documentation

### ISSUE THREAD

**Issue by RobSteele49** [joequant/iraf#1]
If you have some I couldn't find it - I'm just looking for the basic steps to make a linux64 build. Could you let @zcsteele when you have these? Or just let me know the order is it:

./install
./build.sh
./make sysgen

Or whatever you recommend.

**Comment by steelewool** [comment]
Do I just need to run ./build.sh to build the linux64 version?

**Comment by joequant** [comment]
Look at the README for joequant/iraf-v216 under branch linux-build

I've changed the title to mark this repo as obsolete.
