### ISSUE TITLE
Build.sh error: votParse.c:27:20: fatal error: fitsio.h: No such file or directory

### ISSUE THREAD

**Issue by steelewool** [joequant/iraf#2]
Are you seeing this when you run build.sh? I executed 'build.sh' from a clean checkout and I'm getting this error. This happened on our copy of your linux-build branch after @zcsteele had made an update.

I could fix this by putting in the path to the fitsio.h file - but I was wondering you had a more long term fix than changing the .c file.

**Comment by joequant** [comment]
The build script expects an external cfitsio library so you have to make
sure that that's installed on your system.  The file should be in
/usr/include

**Comment by steelewool** [comment]
Is there some document on the IRAF site that I should read to let me know what external libraries (such as cfitso) that I need. I would help @zcsteele & I to be able to compile correctly?

**Comment by RobSteele49** [comment]
My apologies, I just looked over your README.md file and you reference several RPM packages that I'm assuming I need to have to be able to build correctly. @zcsteele (did you see those)?

**Comment by joequant** [comment]
Yes.

You should use the tree joequant/iraf-v216 branch linux-build which makes
the changes match the iraf tree.  There is a README.md file.  I'll update
the file with build instructions.

**Comment by joequant** [comment]
I'll put in a note not to use joequant/iraf but rather joequant/iraf-v216
which tracks iraf official tree on github.

**Comment by steelewool** [comment]
We (@zcsteele) and myself are indeed using the iraf-v216 repository.

**Comment by zcsteele** [comment]
@joequant - Creating new tickets seems to be disabled on your 'iraf-v216' repository, so I'm leaving relevant comments here as a workaround.

I built a copy of cfitsio in Cygwin using the code present in vendor/cfitsio, and that resolved this issue.  Also, I spoke with @RobSteele49 offline and he was similarly successful when installing cfitsio using 'apt-get' on Ubuntu.

Thanks for your help!

**Comment by joequant** [comment]
Also if you can modify README.md in iraf-v216 to include exactly what
packages need to be added to Ubuntu, this would be highly useful.  Also I'd
also be interested if someone can put in a script to generate a dpkg with
iraf.
